# Generated by Django 5.2.16 on 2026-07-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_availabilityexception_uniq_availability_exception_tutor_date"),
        ("payments", "0002_payment_captured_amount_paymentstatustransition"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("captured_amount__lte", models.F("amount"))),
                name="payment_captured_le_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("commission__lte", models.F("captured_amount"))),
                name="payment_commission_le_captured",
            ),
        ),
    ]
