# Generated by Django 5.2.16 on 2026-07-12 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_processedwebhookevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="retained_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("retained_amount__lte", models.F("amount"))),
                name="payment_retained_le_amount",
            ),
        ),
    ]
