# Generated by Django 5.2.16 on 2026-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_no_overlap_gist"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availabilityexception",
            constraint=models.UniqueConstraint(
                fields=("tutor", "date"), name="uniq_availability_exception_tutor_date"
            ),
        ),
    ]
