# Generated by Django 5.2.16 on 2026-07-08 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                ("video_intro_url", models.URLField(blank=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("education", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "late_cancellation_refund_percent",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("lessons_count", models.PositiveIntegerField(default=0)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=100)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_subjects",
                        to="catalog.subject",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_subjects",
                        to="catalog.tutorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.ManyToManyField(
                related_name="tutors", through="catalog.TutorSubject", to="catalog.subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="tutorsubject",
            constraint=models.UniqueConstraint(
                fields=("tutor", "subject", "level"), name="uniq_tutor_subject_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="tutorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("late_cancellation_refund_percent__lte", 100)),
                name="tutor_late_cancel_percent_lte_100",
            ),
        ),
    ]
